"""Seed catalog loaded into Postgres by scripts/seed_db.py.

This is the starting data set for the "search for your vehicle" feature --
expand this list (or replace it with a proper import pipeline) as more
vehicles get sourced.
"""

SEED_VEHICLES = [
    {"type": "car", "make": "Toyota", "model": "GR86", "year": 2024, "engine": "2.4L Flat-4",
     "horsepower": 228, "torque": 184, "zero_to_sixty": 6.1, "top_speed": 140, "weight": 2811,
     "price": 28400, "drivetrain": "RWD", "body_style": "Coupe"},
    {"type": "car", "make": "Mazda", "model": "MX-5 Miata", "year": 2024, "engine": "2.0L I4",
     "horsepower": 181, "torque": 151, "zero_to_sixty": 6.5, "top_speed": 135, "weight": 2341,
     "price": 29050, "drivetrain": "RWD", "body_style": "Convertible"},
    {"type": "car", "make": "Honda", "model": "Civic Type R", "year": 2024, "engine": "2.0L Turbo I4",
     "horsepower": 315, "torque": 310, "zero_to_sixty": 5.0, "top_speed": 170, "weight": 3188,
     "price": 44890, "drivetrain": "FWD", "body_style": "Hatchback"},
    {"type": "car", "make": "Ford", "model": "Mustang GT", "year": 2024, "engine": "5.0L V8",
     "horsepower": 480, "torque": 415, "zero_to_sixty": 4.3, "top_speed": 155, "weight": 3705,
     "price": 44090, "drivetrain": "RWD", "body_style": "Coupe"},
    {"type": "car", "make": "Chevrolet", "model": "Camaro SS", "year": 2024, "engine": "6.2L V8",
     "horsepower": 455, "torque": 455, "zero_to_sixty": 4.0, "top_speed": 165, "weight": 3685,
     "price": 42395, "drivetrain": "RWD", "body_style": "Coupe"},
    {"type": "car", "make": "Subaru", "model": "WRX", "year": 2024, "engine": "2.4L Turbo Flat-4",
     "horsepower": 271, "torque": 258, "zero_to_sixty": 5.7, "top_speed": 155, "weight": 3300,
     "price": 33825, "drivetrain": "AWD", "body_style": "Sedan"},
    {"type": "car", "make": "Volkswagen", "model": "Golf GTI", "year": 2024, "engine": "2.0L Turbo I4",
     "horsepower": 241, "torque": 273, "zero_to_sixty": 5.8, "top_speed": 155, "weight": 3131,
     "price": 31215, "drivetrain": "FWD", "body_style": "Hatchback"},
    {"type": "car", "make": "BMW", "model": "M3", "year": 2024, "engine": "3.0L Twin-Turbo I6",
     "horsepower": 473, "torque": 406, "zero_to_sixty": 3.8, "top_speed": 180, "weight": 3880,
     "price": 76395, "drivetrain": "AWD", "body_style": "Sedan"},
    {"type": "car", "make": "Porsche", "model": "911 Carrera", "year": 2024, "engine": "3.0L Twin-Turbo Flat-6",
     "horsepower": 379, "torque": 331, "zero_to_sixty": 4.0, "top_speed": 182, "weight": 3354,
     "price": 106100, "drivetrain": "RWD", "body_style": "Coupe"},
    {"type": "car", "make": "Tesla", "model": "Model 3 Performance", "year": 2024, "engine": "Dual Motor Electric",
     "horsepower": 510, "torque": 546, "zero_to_sixty": 2.9, "top_speed": 163, "weight": 4054,
     "price": 52990, "drivetrain": "AWD", "body_style": "Sedan"},
    {"type": "car", "make": "Nissan", "model": "Z", "year": 2024, "engine": "3.0L Twin-Turbo V6",
     "horsepower": 400, "torque": 350, "zero_to_sixty": 4.5, "top_speed": 155, "weight": 3486,
     "price": 42990, "drivetrain": "RWD", "body_style": "Coupe"},
    {"type": "car", "make": "Dodge", "model": "Challenger R/T", "year": 2023, "engine": "5.7L V8",
     "horsepower": 375, "torque": 410, "zero_to_sixty": 5.1, "top_speed": 155, "weight": 4185,
     "price": 39590, "drivetrain": "RWD", "body_style": "Coupe"},
    {"type": "car", "make": "Toyota", "model": "GR Supra", "year": 2024, "engine": "3.0L Turbo I6",
     "horsepower": 382, "torque": 368, "zero_to_sixty": 3.9, "top_speed": 155, "weight": 3400,
     "price": 55250, "drivetrain": "RWD", "body_style": "Coupe"},
    {"type": "car", "make": "Hyundai", "model": "Elantra N", "year": 2024, "engine": "2.0L Turbo I4",
     "horsepower": 276, "torque": 289, "zero_to_sixty": 5.3, "top_speed": 155, "weight": 3163,
     "price": 34000, "drivetrain": "FWD", "body_style": "Sedan"},
    {"type": "car", "make": "Kia", "model": "Stinger GT", "year": 2023, "engine": "3.3L Twin-Turbo V6",
     "horsepower": 368, "torque": 376, "zero_to_sixty": 4.7, "top_speed": 167, "weight": 3958,
     "price": 44785, "drivetrain": "AWD", "body_style": "Hatchback"},
    {"type": "motorbike", "make": "Yamaha", "model": "YZF-R6", "year": 2020, "engine": "599cc I4",
     "horsepower": 118, "torque": 46, "zero_to_sixty": 3.3, "top_speed": 160, "weight": 419,
     "price": 12299, "drivetrain": "Chain", "bike_style": "Sport"},
    {"type": "motorbike", "make": "Kawasaki", "model": "Ninja ZX-6R", "year": 2024, "engine": "636cc I4",
     "horsepower": 127, "torque": 52, "zero_to_sixty": 3.2, "top_speed": 165, "weight": 431,
     "price": 11299, "drivetrain": "Chain", "bike_style": "Sport"},
    {"type": "motorbike", "make": "Honda", "model": "CBR600RR", "year": 2024, "engine": "599cc I4",
     "horsepower": 121, "torque": 48, "zero_to_sixty": 3.4, "top_speed": 160, "weight": 410,
     "price": 12599, "drivetrain": "Chain", "bike_style": "Sport"},
    {"type": "motorbike", "make": "Suzuki", "model": "GSX-R750", "year": 2023, "engine": "750cc I4",
     "horsepower": 148, "torque": 63, "zero_to_sixty": 3.0, "top_speed": 165, "weight": 419,
     "price": 12849, "drivetrain": "Chain", "bike_style": "Sport"},
    {"type": "motorbike", "make": "Ducati", "model": "Panigale V4", "year": 2024, "engine": "1103cc V4",
     "horsepower": 214, "torque": 91, "zero_to_sixty": 2.6, "top_speed": 186, "weight": 439,
     "price": 23495, "drivetrain": "Chain", "bike_style": "Sport"},
    {"type": "motorbike", "make": "Harley-Davidson", "model": "Iron 883", "year": 2022, "engine": "883cc V-Twin",
     "horsepower": 50, "torque": 54, "zero_to_sixty": 4.5, "top_speed": 100, "weight": 564,
     "price": 9499, "drivetrain": "Belt", "bike_style": "Cruiser"},
    {"type": "motorbike", "make": "Triumph", "model": "Street Triple RS", "year": 2024, "engine": "765cc I3",
     "horsepower": 128, "torque": 59, "zero_to_sixty": 3.1, "top_speed": 165, "weight": 417,
     "price": 12595, "drivetrain": "Chain", "bike_style": "Naked"},
    {"type": "motorbike", "make": "KTM", "model": "390 Duke", "year": 2024, "engine": "399cc Single",
     "horsepower": 44, "torque": 29, "zero_to_sixty": 5.5, "top_speed": 107, "weight": 348,
     "price": 5999, "drivetrain": "Chain", "bike_style": "Naked"},
    {"type": "motorbike", "make": "BMW", "model": "S1000RR", "year": 2024, "engine": "999cc I4",
     "horsepower": 205, "torque": 83, "zero_to_sixty": 2.7, "top_speed": 188, "weight": 434,
     "price": 18545, "drivetrain": "Chain", "bike_style": "Sport"},
    {"type": "motorbike", "make": "Yamaha", "model": "MT-07", "year": 2024, "engine": "689cc Twin",
     "horsepower": 73, "torque": 50, "zero_to_sixty": 3.7, "top_speed": 130, "weight": 406,
     "price": 8199, "drivetrain": "Chain", "bike_style": "Naked"},
    {"type": "motorbike", "make": "Honda", "model": "Africa Twin", "year": 2024, "engine": "1084cc Twin",
     "horsepower": 101, "torque": 77, "zero_to_sixty": 3.8, "top_speed": 130, "weight": 502,
     "price": 14899, "drivetrain": "Chain", "bike_style": "Adventure"},
    {"type": "motorbike", "make": "Kawasaki", "model": "Z900", "year": 2024, "engine": "948cc I4",
     "horsepower": 125, "torque": 72, "zero_to_sixty": 3.2, "top_speed": 155, "weight": 467,
     "price": 9199, "drivetrain": "Chain", "bike_style": "Naked"},
    {"type": "motorbike", "make": "Ducati", "model": "Monster", "year": 2024, "engine": "937cc Twin",
     "horsepower": 111, "torque": 69, "zero_to_sixty": 3.3, "top_speed": 150, "weight": 414,
     "price": 12995, "drivetrain": "Chain", "bike_style": "Naked"},
    {"type": "motorbike", "make": "Royal Enfield", "model": "Interceptor 650", "year": 2024, "engine": "648cc Twin",
     "horsepower": 47, "torque": 38, "zero_to_sixty": 6.5, "top_speed": 115, "weight": 445,
     "price": 6799, "drivetrain": "Chain", "bike_style": "Cafe racer"},
    {"type": "motorbike", "make": "Suzuki", "model": "Hayabusa", "year": 2024, "engine": "1340cc I4",
     "horsepower": 190, "torque": 111, "zero_to_sixty": 2.6, "top_speed": 186, "weight": 582,
     "price": 18799, "drivetrain": "Chain", "bike_style": "Sport"},
]
